@startuml ドメインモデル図
skinparam componentStyle rectangle

[配送] o-- [配送日時]
[配送] o-- [配送先名]
[配送] o-- [配送時間帯]
[配送] o-- [注文]
[配送] o-- [住所]

[決済ログ] o-- [決済ID]
[決済ログ] o-- [決済金額]
[決済ログ] o-- [決済日時]
[決済ログ] o-- [結果]
[決済ログ] o-- [注文ID]
[決済ログ] o-- [ユーザーID]

[顧客] o-- [氏名]
[顧客] o-- [カート]
[顧客] o-- [住所]
[顧客] o-- [ユーザーID]
[顧客] o-- [メールアドレス]
[顧客] o-- [電話番号]

[管理者] o-- [氏名]
[管理者] o-- [管理者ID]
[管理者] o-- [決済履歴]
[管理者] o-- [種別]

[注文] o-- [注文日時]
[注文] o-- [注文ID]
[注文] o-- [合計金額]
[注文] o-- [出荷状況]
[注文] o-- [決済]
[注文] o-- [ユーザーID]
[注文] o-- [注文詳細]

[カート] o-- [数量]
[カート] o-- [商品]

[商品] o-- [商品ID]
[商品] o-- [商品名]
[商品] o-- [単価]
[商品] o-- [在庫]

[注文詳細] o-- [小計]
[注文詳細] o-- [個数]
[注文詳細] o-- [商品]

[返品] o-- [返金金額]
[返品] o-- [返品日時]
[返品] o-- [返品状況]
[返品] o-- [返品ID]
[返品] o-- [返金日時]
[返品] o-- [返品理由]
[返品] o-- [注文詳細]

[出荷状況] <|-- [出荷準備中]
[出荷状況] <|-- [出荷待ち]
[出荷状況] <|-- [出荷済み]

[返品理由] <|-- [購入者都合]
[返品理由] <|-- [販売者都合]

[購入者都合] <|-- [商品が気に入らなかった]
[販売者都合] <|-- [商品の破損]

[種別] <|-- [顧客情報管理者]
[種別] <|-- [社内商品管理者]
[種別] <|-- [カスタマサポート]

[返品状況] <|-- [発送待ち]
[返品状況] <|-- [発送中]
[返品状況] <|-- [到着済み]

@enduml