@startuml ドメインモデル図
skinparam componentStyle rectangle

[ユーザー] o-- [氏名]
[ユーザー] o-- [カート]
[ユーザー] o-- [住所]
[ユーザー] o-- [ユーザーID]
[ユーザー] o-- [メールアドレス]
[ユーザー] o-- [電話番号]

[注文] o-- [注文日]
[注文] o-- [注文ID]
[注文] o-- [合計金額]
[注文] o-- [出荷状況]
[注文] o-- [決済]

[商品] o-- [商品ID]
[商品] o-- [商品名]
[商品] o-- [単価]
[商品] o-- [在庫]

[カート] o-- [数量]
[カート] o-- [商品]

[決済] <|-- [クレジットカード決済]

[出荷状況] o-- [出荷準備中]
[出荷状況] o-- [出荷待ち]
[出荷状況] o-- [出荷済み]

[返品] o-- [返金処理]
[返品] o-- [返品理由]
[返品] o-- [返品ID]
@enduml