@startuml ドメインモデル図
skinparam componentStyle rectangle


[ルイ・フィトン注文販売サイト] o-- [顧客]
[ルイ・フィトン注文販売サイト] o-- [注文]
[ルイ・フィトン注文販売サイト] o-- [商品]

[ルイ・フィトン注文販売システム] o-- [配送]
[ルイ・フィトン注文販売システム] o-- [返品]

[顧客] o-- [氏名]
[顧客] o-- [顧客ID]
[顧客] o-- [住所]
[顧客] o-- [クレジットカード情報]
[顧客] o-- [メールアドレス]
[顧客] o-- [電話番号]

[注文] o-- [注文日]
[注文] o-- [注文ID]
[注文] o-- [合計金額]
[注文] o-- [注文詳細]
[注文] o-- [決済]

[商品] o-- [商品ID]
[商品] o-- [商品名]
[商品] o-- [単価]
[商品] o-- [在庫]
[商品] o-- [カート]

[カート] o-- [数量]

[決済] <|-- [クレジットカード決済]

[配送] o-- [発送ID]
[配送] o-- [発送日]
[配送] o-- [到着]
[配送] o-- [追跡番号]

[返品] o-- [返金処理]
[返品] o-- [返品理由]
[返品] o-- [返品ID]
@enduml