@startuml
left to right direction

actor 顧客
actor 管理者
actor カスタマーサポート
actor 発送業者

rectangle "ルイ・フィトン注文販売システム" {

  ' --- 管理者 ---
  (在庫管理)
  (注文内容確認)
  (発送処理)
  (到着確認)
  (キャンセル対応)

  ' --- システム自動処理 ---
  (決済完了メール送信)
  (発送完了メール送信)
  (到着完了メール送信)
}


rectangle "ルイ・フィトン注文販売サイト" {
    ' --- 顧客 ---
  (ログイン)
  (商品検索)
  (カートに入れる)
  (支払い)
  (購入確定)
  (レビュー投稿)
  (キャンセル申請)
  (商品購入画面)
}


' 顧客の動き
顧客 --> (ログイン)
顧客 --> (商品検索)
顧客 --> (カートに入れる)
顧客 --> (支払い)
顧客 --> (購入確定)
顧客 --> (レビュー投稿)
顧客 --> (キャンセル申請)
顧客 --> (商品購入画面)

' 管理者などの動き
管理者 --> (在庫管理)
管理者 --> (注文内容確認)
' システムの自動処理
管理者 --> (決済完了メール送信)
管理者 --> (発送完了メール送信)
管理者 --> (到着完了メール送信)
'発送業者とカスタマーサポートの追加
発送業者 --> (発送処理)
発送業者 --> (到着確認)
カスタマーサポート --> (キャンセル対応)



' 自動処理の結果は顧客に通知
(決済完了メール送信) --> 顧客
(発送完了メール送信) --> 顧客
(到着完了メール送信) --> 顧客

@enduml
