@startuml
left to right direction

actor 顧客
actor カスタマーサポート
actor 発送業者
actor 在庫管理者
actor 商品管理者
actor 顧客情報管理者
actor サイトコンテンツ管理

rectangle "ルイ・フィトン注文販売システム" {

  ' --- 管理者 ---
  (発送処理)

  (キャンセルメール対応)
  (返品対応)
  (返金対応)
  (お問い合わせ対応)

  (在庫入荷)
  (在庫出荷)
  (在庫切れ通知)

  (売り上げデータ集計)
  (売り上げデータ分析)

  '--- 顧客情報管理者 ---
  (顧客情報登録)
  (顧客情報更新)
  (顧客情報削除)
  (顧客注文履歴管理)

  (サイト更新)
  (サイト運営・保守)

}


rectangle "ルイ・フィトン注文販売サイト" {
    ' --- 顧客 ---
  (ログイン)
  (ログアウト)
  (新規登録)
  (商品検索)
  (カートに追加)
  (カートの削除)
  (注文履歴)
  (支払い)
  (購入確定)
  (レビュー投稿)
  (キャンセル申請)
  (商品購入画面)
  (お問い合わせ)
}


' 顧客の動き
顧客 --> (ログイン)
顧客 --> (ログアウト)
顧客 --> (商品検索)
顧客 --> (カートに追加)
顧客 --> (カートの削除)
顧客 --> (注文履歴)
顧客 --> (新規登録)
顧客 --> (支払い)
顧客 --> (購入確定)
顧客 --> (レビュー投稿)
顧客 --> (キャンセル申請)
顧客 --> (商品購入画面)
顧客 --> (お問い合わせ)

' 管理者などの動き
在庫管理者 --> (在庫入荷)
在庫管理者 --> (在庫出荷)
在庫管理者 --> (在庫切れ通知)

商品管理者 --> (売り上げデータ集計)
商品管理者 --> (売り上げデータ分析)

'発送業者とカスタマーサポートの追加
発送業者 --> (発送処理)

カスタマーサポート --> (キャンセルメール対応)
カスタマーサポート --> (返品対応)
カスタマーサポート --> (返金対応)
カスタマーサポート --> (お問い合わせ対応)

顧客情報管理者 --> (顧客情報登録)
顧客情報管理者 --> (顧客情報更新)
顧客情報管理者 --> (顧客情報削除)
顧客情報管理者 --> (顧客注文履歴管理)

サイトコンテンツ管理 --> (サイト更新)
サイトコンテンツ管理 --> (サイト運営・保守)

@enduml
